/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Nov 27 02:44:03 2019. */

#include "ledctrl.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledctrl_Request_fields[9] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_Request, id, id, 0),
    PB_ONEOF_FIELD(request,   2, MESSAGE , ONEOF, STATIC  , OTHER, ledctrl_Request, clear, id, &ledctrl_ClearRequest_fields),
    PB_ONEOF_FIELD(request,   3, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, brightness, id, &ledctrl_BrightnessRequest_fields),
    PB_ONEOF_FIELD(request,   4, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, pixels, id, &ledctrl_PixelsRequest_fields),
    PB_ONEOF_FIELD(request,   5, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, draw_line, id, &ledctrl_DrawLineRequest_fields),
    PB_ONEOF_FIELD(request,   6, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, dimension, id, &ledctrl_DimensionRequest_fields),
    PB_ONEOF_FIELD(request,   7, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, update, id, &ledctrl_UpdateRequest_fields),
    PB_ONEOF_FIELD(request,   8, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, raw, id, &ledctrl_RawRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_Response_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_Response, id, id, 0),
    PB_ONEOF_FIELD(response,   2, MESSAGE , ONEOF, STATIC  , OTHER, ledctrl_Response, empty, id, &ledctrl_EmptyResponse_fields),
    PB_ONEOF_FIELD(response,   3, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Response, dimension, id, &ledctrl_DimensionResponse_fields),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_Coord_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_Coord, xy, xy, 0),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_PixelColor_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledctrl_PixelColor, color, color, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ledctrl_PixelColor, coord, color, &ledctrl_Coord_fields),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_ClearRequest_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledctrl_ClearRequest, color, color, 0),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_RawRequest_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_RawRequest, index, index, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, ledctrl_RawRequest, pixels, index, 0),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_PixelsRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, ledctrl_PixelsRequest, pixels, pixels, &ledctrl_PixelColor_fields),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_BrightnessRequest_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_BrightnessRequest, brightness, brightness, 0),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_DrawLineRequest_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledctrl_DrawLineRequest, color, color, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ledctrl_DrawLineRequest, start, color, &ledctrl_Coord_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, ledctrl_DrawLineRequest, end, start, &ledctrl_Coord_fields),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_DimensionRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ledctrl_EmptyResponse_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ledctrl_UpdateRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ledctrl_DimensionResponse_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_DimensionResponse, width, width, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, ledctrl_DimensionResponse, height, width, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledctrl_Request, request.clear) < 65536 && pb_membersize(ledctrl_Request, request.brightness) < 65536 && pb_membersize(ledctrl_Request, request.pixels) < 65536 && pb_membersize(ledctrl_Request, request.draw_line) < 65536 && pb_membersize(ledctrl_Request, request.dimension) < 65536 && pb_membersize(ledctrl_Request, request.update) < 65536 && pb_membersize(ledctrl_Request, request.raw) < 65536 && pb_membersize(ledctrl_Response, response.empty) < 65536 && pb_membersize(ledctrl_Response, response.dimension) < 65536 && pb_membersize(ledctrl_PixelColor, coord) < 65536 && pb_membersize(ledctrl_PixelsRequest, pixels[0]) < 65536 && pb_membersize(ledctrl_DrawLineRequest, start) < 65536 && pb_membersize(ledctrl_DrawLineRequest, end) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ledctrl_Request_ledctrl_Response_ledctrl_Coord_ledctrl_PixelColor_ledctrl_ClearRequest_ledctrl_RawRequest_ledctrl_PixelsRequest_ledctrl_BrightnessRequest_ledctrl_DrawLineRequest_ledctrl_DimensionRequest_ledctrl_EmptyResponse_ledctrl_UpdateRequest_ledctrl_DimensionResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledctrl_Request, request.clear) < 256 && pb_membersize(ledctrl_Request, request.brightness) < 256 && pb_membersize(ledctrl_Request, request.pixels) < 256 && pb_membersize(ledctrl_Request, request.draw_line) < 256 && pb_membersize(ledctrl_Request, request.dimension) < 256 && pb_membersize(ledctrl_Request, request.update) < 256 && pb_membersize(ledctrl_Request, request.raw) < 256 && pb_membersize(ledctrl_Response, response.empty) < 256 && pb_membersize(ledctrl_Response, response.dimension) < 256 && pb_membersize(ledctrl_PixelColor, coord) < 256 && pb_membersize(ledctrl_PixelsRequest, pixels[0]) < 256 && pb_membersize(ledctrl_DrawLineRequest, start) < 256 && pb_membersize(ledctrl_DrawLineRequest, end) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ledctrl_Request_ledctrl_Response_ledctrl_Coord_ledctrl_PixelColor_ledctrl_ClearRequest_ledctrl_RawRequest_ledctrl_PixelsRequest_ledctrl_BrightnessRequest_ledctrl_DrawLineRequest_ledctrl_DimensionRequest_ledctrl_EmptyResponse_ledctrl_UpdateRequest_ledctrl_DimensionResponse)
#endif


/* @@protoc_insertion_point(eof) */
