/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Sep 10 01:12:14 2019. */

#include "ledctrl.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledctrl_Request_fields[4] = {
    PB_ONEOF_FIELD(request,   1, MESSAGE , ONEOF, STATIC  , FIRST, ledctrl_Request, clear_request, clear_request, &ledctrl_ClearRequest_fields),
    PB_ONEOF_FIELD(request,   2, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, display_image_request, display_image_request, &ledctrl_DisplayImageRequest_fields),
    PB_ONEOF_FIELD(request,   3, MESSAGE , ONEOF, STATIC  , UNION, ledctrl_Request, brightness_request, brightness_request, &ledctrl_BrightnessRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_EmptyResponse_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ledctrl_ClearRequest_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledctrl_ClearRequest, color, color, 0),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_DisplayImageRequest_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, ledctrl_DisplayImageRequest, pixels, pixels, 0),
    PB_LAST_FIELD
};

const pb_field_t ledctrl_BrightnessRequest_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ledctrl_BrightnessRequest, brightness, brightness, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledctrl_Request, request.clear_request) < 65536 && pb_membersize(ledctrl_Request, request.display_image_request) < 65536 && pb_membersize(ledctrl_Request, request.brightness_request) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ledctrl_Request_ledctrl_EmptyResponse_ledctrl_ClearRequest_ledctrl_DisplayImageRequest_ledctrl_BrightnessRequest)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ledctrl_DisplayImageRequest.pixels is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
