/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "pi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(piproto_Request, piproto_Request, 2)


PB_BIND(piproto_Response, piproto_Response, AUTO)


PB_BIND(piproto_Coord, piproto_Coord, AUTO)


PB_BIND(piproto_PixelColor, piproto_PixelColor, AUTO)


PB_BIND(piproto_ClearRequest, piproto_ClearRequest, AUTO)


PB_BIND(piproto_RawRequest, piproto_RawRequest, 2)


PB_BIND(piproto_PixelsRequest, piproto_PixelsRequest, 2)


PB_BIND(piproto_BrightnessRequest, piproto_BrightnessRequest, AUTO)


PB_BIND(piproto_DrawLineRequest, piproto_DrawLineRequest, AUTO)


PB_BIND(piproto_DimensionRequest, piproto_DimensionRequest, AUTO)


PB_BIND(piproto_EmptyResponse, piproto_EmptyResponse, AUTO)


PB_BIND(piproto_UpdateRequest, piproto_UpdateRequest, AUTO)


PB_BIND(piproto_DimensionResponse, piproto_DimensionResponse, AUTO)



