/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Dec 11 21:59:52 2019. */

#include "pi.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t piproto_Request_fields[9] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, piproto_Request, id, id, 0),
    PB_ONEOF_FIELD(request,   2, MESSAGE , ONEOF, STATIC  , OTHER, piproto_Request, clear, id, &piproto_ClearRequest_fields),
    PB_ONEOF_FIELD(request,   3, MESSAGE , ONEOF, STATIC  , UNION, piproto_Request, brightness, id, &piproto_BrightnessRequest_fields),
    PB_ONEOF_FIELD(request,   4, MESSAGE , ONEOF, STATIC  , UNION, piproto_Request, pixels, id, &piproto_PixelsRequest_fields),
    PB_ONEOF_FIELD(request,   5, MESSAGE , ONEOF, STATIC  , UNION, piproto_Request, draw_line, id, &piproto_DrawLineRequest_fields),
    PB_ONEOF_FIELD(request,   6, MESSAGE , ONEOF, STATIC  , UNION, piproto_Request, dimension, id, &piproto_DimensionRequest_fields),
    PB_ONEOF_FIELD(request,   7, MESSAGE , ONEOF, STATIC  , UNION, piproto_Request, update, id, &piproto_UpdateRequest_fields),
    PB_ONEOF_FIELD(request,   8, MESSAGE , ONEOF, STATIC  , UNION, piproto_Request, raw, id, &piproto_RawRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t piproto_Response_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, piproto_Response, id, id, 0),
    PB_ONEOF_FIELD(response,   2, MESSAGE , ONEOF, STATIC  , OTHER, piproto_Response, empty, id, &piproto_EmptyResponse_fields),
    PB_ONEOF_FIELD(response,   3, MESSAGE , ONEOF, STATIC  , UNION, piproto_Response, dimension, id, &piproto_DimensionResponse_fields),
    PB_LAST_FIELD
};

const pb_field_t piproto_Coord_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, piproto_Coord, xy, xy, 0),
    PB_LAST_FIELD
};

const pb_field_t piproto_PixelColor_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, piproto_PixelColor, color, color, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, piproto_PixelColor, coord, color, &piproto_Coord_fields),
    PB_LAST_FIELD
};

const pb_field_t piproto_ClearRequest_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, piproto_ClearRequest, color, color, 0),
    PB_LAST_FIELD
};

const pb_field_t piproto_RawRequest_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, piproto_RawRequest, index, index, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, piproto_RawRequest, pixels, index, 0),
    PB_LAST_FIELD
};

const pb_field_t piproto_PixelsRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, piproto_PixelsRequest, pixels, pixels, &piproto_PixelColor_fields),
    PB_LAST_FIELD
};

const pb_field_t piproto_BrightnessRequest_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, piproto_BrightnessRequest, brightness, brightness, 0),
    PB_LAST_FIELD
};

const pb_field_t piproto_DrawLineRequest_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, piproto_DrawLineRequest, color, color, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, piproto_DrawLineRequest, start, color, &piproto_Coord_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, piproto_DrawLineRequest, end, start, &piproto_Coord_fields),
    PB_LAST_FIELD
};

const pb_field_t piproto_DimensionRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t piproto_EmptyResponse_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t piproto_UpdateRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t piproto_DimensionResponse_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, piproto_DimensionResponse, width, width, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, piproto_DimensionResponse, height, width, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(piproto_Request, request.clear) < 65536 && pb_membersize(piproto_Request, request.brightness) < 65536 && pb_membersize(piproto_Request, request.pixels) < 65536 && pb_membersize(piproto_Request, request.draw_line) < 65536 && pb_membersize(piproto_Request, request.dimension) < 65536 && pb_membersize(piproto_Request, request.update) < 65536 && pb_membersize(piproto_Request, request.raw) < 65536 && pb_membersize(piproto_Response, response.empty) < 65536 && pb_membersize(piproto_Response, response.dimension) < 65536 && pb_membersize(piproto_PixelColor, coord) < 65536 && pb_membersize(piproto_PixelsRequest, pixels[0]) < 65536 && pb_membersize(piproto_DrawLineRequest, start) < 65536 && pb_membersize(piproto_DrawLineRequest, end) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_piproto_Request_piproto_Response_piproto_Coord_piproto_PixelColor_piproto_ClearRequest_piproto_RawRequest_piproto_PixelsRequest_piproto_BrightnessRequest_piproto_DrawLineRequest_piproto_DimensionRequest_piproto_EmptyResponse_piproto_UpdateRequest_piproto_DimensionResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(piproto_Request, request.clear) < 256 && pb_membersize(piproto_Request, request.brightness) < 256 && pb_membersize(piproto_Request, request.pixels) < 256 && pb_membersize(piproto_Request, request.draw_line) < 256 && pb_membersize(piproto_Request, request.dimension) < 256 && pb_membersize(piproto_Request, request.update) < 256 && pb_membersize(piproto_Request, request.raw) < 256 && pb_membersize(piproto_Response, response.empty) < 256 && pb_membersize(piproto_Response, response.dimension) < 256 && pb_membersize(piproto_PixelColor, coord) < 256 && pb_membersize(piproto_PixelsRequest, pixels[0]) < 256 && pb_membersize(piproto_DrawLineRequest, start) < 256 && pb_membersize(piproto_DrawLineRequest, end) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_piproto_Request_piproto_Response_piproto_Coord_piproto_PixelColor_piproto_ClearRequest_piproto_RawRequest_piproto_PixelsRequest_piproto_BrightnessRequest_piproto_DrawLineRequest_piproto_DimensionRequest_piproto_EmptyResponse_piproto_UpdateRequest_piproto_DimensionResponse)
#endif


/* @@protoc_insertion_point(eof) */
