// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pi.proto

package pi_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*Request_Clear
	//	*Request_Brightness
	//	*Request_Pixels
	//	*Request_DrawLine
	//	*Request_Dimension
	//	*Request_Update
	//	*Request_Raw
	Request              isRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isRequest_Request interface {
	isRequest_Request()
}

type Request_Clear struct {
	Clear *ClearRequest `protobuf:"bytes,2,opt,name=clear,proto3,oneof"`
}

type Request_Brightness struct {
	Brightness *BrightnessRequest `protobuf:"bytes,3,opt,name=brightness,proto3,oneof"`
}

type Request_Pixels struct {
	Pixels *PixelsRequest `protobuf:"bytes,4,opt,name=pixels,proto3,oneof"`
}

type Request_DrawLine struct {
	DrawLine *DrawLineRequest `protobuf:"bytes,5,opt,name=draw_line,json=drawLine,proto3,oneof"`
}

type Request_Dimension struct {
	Dimension *DimensionRequest `protobuf:"bytes,6,opt,name=dimension,proto3,oneof"`
}

type Request_Update struct {
	Update *UpdateRequest `protobuf:"bytes,7,opt,name=update,proto3,oneof"`
}

type Request_Raw struct {
	Raw *RawRequest `protobuf:"bytes,8,opt,name=raw,proto3,oneof"`
}

func (*Request_Clear) isRequest_Request() {}

func (*Request_Brightness) isRequest_Request() {}

func (*Request_Pixels) isRequest_Request() {}

func (*Request_DrawLine) isRequest_Request() {}

func (*Request_Dimension) isRequest_Request() {}

func (*Request_Update) isRequest_Request() {}

func (*Request_Raw) isRequest_Request() {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetClear() *ClearRequest {
	if x, ok := m.GetRequest().(*Request_Clear); ok {
		return x.Clear
	}
	return nil
}

func (m *Request) GetBrightness() *BrightnessRequest {
	if x, ok := m.GetRequest().(*Request_Brightness); ok {
		return x.Brightness
	}
	return nil
}

func (m *Request) GetPixels() *PixelsRequest {
	if x, ok := m.GetRequest().(*Request_Pixels); ok {
		return x.Pixels
	}
	return nil
}

func (m *Request) GetDrawLine() *DrawLineRequest {
	if x, ok := m.GetRequest().(*Request_DrawLine); ok {
		return x.DrawLine
	}
	return nil
}

func (m *Request) GetDimension() *DimensionRequest {
	if x, ok := m.GetRequest().(*Request_Dimension); ok {
		return x.Dimension
	}
	return nil
}

func (m *Request) GetUpdate() *UpdateRequest {
	if x, ok := m.GetRequest().(*Request_Update); ok {
		return x.Update
	}
	return nil
}

func (m *Request) GetRaw() *RawRequest {
	if x, ok := m.GetRequest().(*Request_Raw); ok {
		return x.Raw
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Clear)(nil),
		(*Request_Brightness)(nil),
		(*Request_Pixels)(nil),
		(*Request_DrawLine)(nil),
		(*Request_Dimension)(nil),
		(*Request_Update)(nil),
		(*Request_Raw)(nil),
	}
}

type Response struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*Response_Empty
	//	*Response_Dimension
	Response             isResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_Empty struct {
	Empty *EmptyResponse `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type Response_Dimension struct {
	Dimension *DimensionResponse `protobuf:"bytes,3,opt,name=dimension,proto3,oneof"`
}

func (*Response_Empty) isResponse_Response() {}

func (*Response_Dimension) isResponse_Response() {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetEmpty() *EmptyResponse {
	if x, ok := m.GetResponse().(*Response_Empty); ok {
		return x.Empty
	}
	return nil
}

func (m *Response) GetDimension() *DimensionResponse {
	if x, ok := m.GetResponse().(*Response_Dimension); ok {
		return x.Dimension
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Empty)(nil),
		(*Response_Dimension)(nil),
	}
}

type Coord struct {
	Xy                   int32    `protobuf:"varint,1,opt,name=xy,proto3" json:"xy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{2}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetXy() int32 {
	if m != nil {
		return m.Xy
	}
	return 0
}

type PixelColor struct {
	Color                uint32   `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	Coord                *Coord   `protobuf:"bytes,2,opt,name=coord,proto3" json:"coord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixelColor) Reset()         { *m = PixelColor{} }
func (m *PixelColor) String() string { return proto.CompactTextString(m) }
func (*PixelColor) ProtoMessage()    {}
func (*PixelColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{3}
}

func (m *PixelColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixelColor.Unmarshal(m, b)
}
func (m *PixelColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixelColor.Marshal(b, m, deterministic)
}
func (m *PixelColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixelColor.Merge(m, src)
}
func (m *PixelColor) XXX_Size() int {
	return xxx_messageInfo_PixelColor.Size(m)
}
func (m *PixelColor) XXX_DiscardUnknown() {
	xxx_messageInfo_PixelColor.DiscardUnknown(m)
}

var xxx_messageInfo_PixelColor proto.InternalMessageInfo

func (m *PixelColor) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *PixelColor) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type ClearRequest struct {
	Color                uint32   `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{4}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

//
//Copy raw byte into LED data
type RawRequest struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Pixels               []int32  `protobuf:"varint,2,rep,packed,name=pixels,proto3" json:"pixels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawRequest) Reset()         { *m = RawRequest{} }
func (m *RawRequest) String() string { return proto.CompactTextString(m) }
func (*RawRequest) ProtoMessage()    {}
func (*RawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{5}
}

func (m *RawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRequest.Unmarshal(m, b)
}
func (m *RawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRequest.Marshal(b, m, deterministic)
}
func (m *RawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRequest.Merge(m, src)
}
func (m *RawRequest) XXX_Size() int {
	return xxx_messageInfo_RawRequest.Size(m)
}
func (m *RawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawRequest proto.InternalMessageInfo

func (m *RawRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RawRequest) GetPixels() []int32 {
	if m != nil {
		return m.Pixels
	}
	return nil
}

//
//Update a list of pixel
type PixelsRequest struct {
	Pixels               []*PixelColor `protobuf:"bytes,1,rep,name=pixels,proto3" json:"pixels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PixelsRequest) Reset()         { *m = PixelsRequest{} }
func (m *PixelsRequest) String() string { return proto.CompactTextString(m) }
func (*PixelsRequest) ProtoMessage()    {}
func (*PixelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{6}
}

func (m *PixelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixelsRequest.Unmarshal(m, b)
}
func (m *PixelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixelsRequest.Marshal(b, m, deterministic)
}
func (m *PixelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixelsRequest.Merge(m, src)
}
func (m *PixelsRequest) XXX_Size() int {
	return xxx_messageInfo_PixelsRequest.Size(m)
}
func (m *PixelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PixelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PixelsRequest proto.InternalMessageInfo

func (m *PixelsRequest) GetPixels() []*PixelColor {
	if m != nil {
		return m.Pixels
	}
	return nil
}

type BrightnessRequest struct {
	Brightness           int32    `protobuf:"varint,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrightnessRequest) Reset()         { *m = BrightnessRequest{} }
func (m *BrightnessRequest) String() string { return proto.CompactTextString(m) }
func (*BrightnessRequest) ProtoMessage()    {}
func (*BrightnessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{7}
}

func (m *BrightnessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrightnessRequest.Unmarshal(m, b)
}
func (m *BrightnessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrightnessRequest.Marshal(b, m, deterministic)
}
func (m *BrightnessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrightnessRequest.Merge(m, src)
}
func (m *BrightnessRequest) XXX_Size() int {
	return xxx_messageInfo_BrightnessRequest.Size(m)
}
func (m *BrightnessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrightnessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrightnessRequest proto.InternalMessageInfo

func (m *BrightnessRequest) GetBrightness() int32 {
	if m != nil {
		return m.Brightness
	}
	return 0
}

type DrawLineRequest struct {
	Color                uint32   `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	Start                *Coord   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Coord   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawLineRequest) Reset()         { *m = DrawLineRequest{} }
func (m *DrawLineRequest) String() string { return proto.CompactTextString(m) }
func (*DrawLineRequest) ProtoMessage()    {}
func (*DrawLineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{8}
}

func (m *DrawLineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawLineRequest.Unmarshal(m, b)
}
func (m *DrawLineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawLineRequest.Marshal(b, m, deterministic)
}
func (m *DrawLineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawLineRequest.Merge(m, src)
}
func (m *DrawLineRequest) XXX_Size() int {
	return xxx_messageInfo_DrawLineRequest.Size(m)
}
func (m *DrawLineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawLineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawLineRequest proto.InternalMessageInfo

func (m *DrawLineRequest) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *DrawLineRequest) GetStart() *Coord {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *DrawLineRequest) GetEnd() *Coord {
	if m != nil {
		return m.End
	}
	return nil
}

type DimensionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DimensionRequest) Reset()         { *m = DimensionRequest{} }
func (m *DimensionRequest) String() string { return proto.CompactTextString(m) }
func (*DimensionRequest) ProtoMessage()    {}
func (*DimensionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{9}
}

func (m *DimensionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DimensionRequest.Unmarshal(m, b)
}
func (m *DimensionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DimensionRequest.Marshal(b, m, deterministic)
}
func (m *DimensionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DimensionRequest.Merge(m, src)
}
func (m *DimensionRequest) XXX_Size() int {
	return xxx_messageInfo_DimensionRequest.Size(m)
}
func (m *DimensionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DimensionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DimensionRequest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{10}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type UpdateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{11}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

type DimensionResponse struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DimensionResponse) Reset()         { *m = DimensionResponse{} }
func (m *DimensionResponse) String() string { return proto.CompactTextString(m) }
func (*DimensionResponse) ProtoMessage()    {}
func (*DimensionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e306efa434d900, []int{12}
}

func (m *DimensionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DimensionResponse.Unmarshal(m, b)
}
func (m *DimensionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DimensionResponse.Marshal(b, m, deterministic)
}
func (m *DimensionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DimensionResponse.Merge(m, src)
}
func (m *DimensionResponse) XXX_Size() int {
	return xxx_messageInfo_DimensionResponse.Size(m)
}
func (m *DimensionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DimensionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DimensionResponse proto.InternalMessageInfo

func (m *DimensionResponse) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *DimensionResponse) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "piproto.Request")
	proto.RegisterType((*Response)(nil), "piproto.Response")
	proto.RegisterType((*Coord)(nil), "piproto.Coord")
	proto.RegisterType((*PixelColor)(nil), "piproto.PixelColor")
	proto.RegisterType((*ClearRequest)(nil), "piproto.ClearRequest")
	proto.RegisterType((*RawRequest)(nil), "piproto.RawRequest")
	proto.RegisterType((*PixelsRequest)(nil), "piproto.PixelsRequest")
	proto.RegisterType((*BrightnessRequest)(nil), "piproto.BrightnessRequest")
	proto.RegisterType((*DrawLineRequest)(nil), "piproto.DrawLineRequest")
	proto.RegisterType((*DimensionRequest)(nil), "piproto.DimensionRequest")
	proto.RegisterType((*EmptyResponse)(nil), "piproto.EmptyResponse")
	proto.RegisterType((*UpdateRequest)(nil), "piproto.UpdateRequest")
	proto.RegisterType((*DimensionResponse)(nil), "piproto.DimensionResponse")
}

func init() { proto.RegisterFile("pi.proto", fileDescriptor_42e306efa434d900) }

var fileDescriptor_42e306efa434d900 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xfd, 0x6c, 0x7f, 0x76, 0x9c, 0xa1, 0x69, 0xd3, 0x05, 0x8a, 0xa9, 0x04, 0xb2, 0x56, 0x95,
	0xc8, 0x85, 0x08, 0x91, 0x03, 0x02, 0x21, 0x55, 0x75, 0x8a, 0xd4, 0x03, 0x07, 0x64, 0x89, 0x0b,
	0x97, 0xe2, 0x74, 0x57, 0x64, 0xa5, 0x74, 0xd7, 0xac, 0x5d, 0x39, 0xb9, 0xf1, 0x1b, 0xf2, 0x8b,
	0xd1, 0xae, 0xd7, 0x5e, 0xdb, 0xa1, 0xa7, 0x78, 0xde, 0xbc, 0xb7, 0x7a, 0x33, 0xf3, 0x02, 0x61,
	0xce, 0xe6, 0xb9, 0x14, 0xa5, 0x40, 0xa3, 0x9c, 0xe9, 0x8f, 0xf3, 0x23, 0x9e, 0x71, 0x91, 0xaf,
	0x6a, 0x18, 0xef, 0x3d, 0x18, 0xa5, 0xf4, 0xf7, 0x03, 0x2d, 0x4a, 0x74, 0x0c, 0x2e, 0x23, 0x91,
	0x13, 0x3b, 0x33, 0x3f, 0x75, 0x19, 0x41, 0x6f, 0xc1, 0xbf, 0xdb, 0xd0, 0x4c, 0x46, 0x6e, 0xec,
	0xcc, 0x9e, 0xbc, 0x7f, 0x3e, 0x37, 0x4f, 0xcc, 0x97, 0x0a, 0x35, 0xaa, 0x9b, 0xff, 0xd2, 0x9a,
	0x85, 0x3e, 0x03, 0xac, 0x24, 0xfb, 0xb5, 0x2e, 0x39, 0x2d, 0x8a, 0xc8, 0xd3, 0x9a, 0xf3, 0x56,
	0x93, 0xb4, 0x2d, 0x2b, 0xec, 0xf0, 0xd1, 0x3b, 0x08, 0x72, 0xb6, 0xa5, 0x9b, 0x22, 0xfa, 0x5f,
	0x2b, 0xcf, 0x5a, 0xe5, 0x37, 0x0d, 0x5b, 0x95, 0xe1, 0xa1, 0x0f, 0x30, 0x26, 0x32, 0xab, 0x6e,
	0x37, 0x8c, 0xd3, 0xc8, 0xd7, 0xa2, 0xa8, 0x15, 0x5d, 0xcb, 0xac, 0xfa, 0xca, 0x38, 0xb5, 0xb2,
	0x90, 0x18, 0x08, 0x7d, 0x84, 0x31, 0x61, 0xf7, 0x94, 0x17, 0x4c, 0xf0, 0x28, 0xd0, 0xc2, 0x97,
	0x56, 0xd8, 0x74, 0xac, 0xd2, 0xb2, 0x95, 0xcb, 0x87, 0x9c, 0x64, 0x25, 0x8d, 0x46, 0x03, 0x97,
	0xdf, 0x35, 0xdc, 0x71, 0x59, 0xf3, 0xd0, 0x1b, 0xf0, 0x64, 0x56, 0x45, 0xa1, 0xa6, 0x3f, 0x6d,
	0xe9, 0x69, 0x56, 0x59, 0xae, 0x62, 0x24, 0x63, 0x18, 0xc9, 0x1a, 0xc1, 0x7b, 0x07, 0xc2, 0x94,
	0x16, 0xb9, 0xe0, 0x05, 0x3d, 0xb8, 0xca, 0x1c, 0x7c, 0x7a, 0x9f, 0x97, 0x3b, 0x73, 0x15, 0xeb,
	0xe0, 0x8b, 0x42, 0x1b, 0x99, 0x3a, 0x8b, 0xa6, 0xa1, 0x4f, 0xdd, 0x69, 0x87, 0x57, 0xe9, 0x4c,
	0xdb, 0xea, 0x2c, 0x3d, 0x01, 0x08, 0xa5, 0x69, 0xe0, 0x17, 0xe0, 0x2f, 0x85, 0x90, 0x44, 0x19,
	0xda, 0xee, 0x1a, 0x43, 0xdb, 0x1d, 0xbe, 0x01, 0xd0, 0x27, 0x5a, 0x8a, 0x8d, 0x90, 0xe8, 0x19,
	0xf8, 0x77, 0xea, 0x43, 0x13, 0x26, 0x69, 0x5d, 0xa0, 0x0b, 0x85, 0x0a, 0x49, 0x8c, 0xe9, 0x63,
	0x1b, 0x25, 0x85, 0xa6, 0x75, 0x13, 0x5f, 0xc0, 0x51, 0x37, 0x5a, 0xff, 0x7e, 0x0b, 0x5f, 0x01,
	0xd8, 0xed, 0x29, 0x0e, 0xe3, 0x84, 0x6e, 0x8d, 0xa1, 0xba, 0x40, 0xaf, 0xda, 0x34, 0xb9, 0xb1,
	0x37, 0xf3, 0x13, 0x7f, 0x7f, 0xe9, 0x4e, 0x7f, 0x36, 0xd1, 0xc1, 0xd7, 0x30, 0xe9, 0xa5, 0x0a,
	0x2d, 0x5a, 0xbe, 0x13, 0x7b, 0xbd, 0x43, 0xd9, 0xd1, 0x92, 0x60, 0x7f, 0xe9, 0x4d, 0xff, 0x38,
	0xed, 0x2b, 0x0b, 0x38, 0x3d, 0x48, 0x35, 0x7a, 0xdd, 0xfb, 0x17, 0xd4, 0xa6, 0x3a, 0x08, 0x16,
	0x70, 0x32, 0xc8, 0xe6, 0xe3, 0x2b, 0x2b, 0xca, 0x4c, 0x96, 0x8f, 0xad, 0x4c, 0x37, 0x51, 0x0c,
	0x1e, 0xe5, 0xc4, 0xdc, 0x75, 0xc8, 0x51, 0x2d, 0x8c, 0x60, 0x3a, 0xcc, 0x34, 0x3e, 0x81, 0x49,
	0x2f, 0x2d, 0x0a, 0xe8, 0x05, 0x18, 0x5f, 0xc1, 0xe9, 0x41, 0x36, 0x94, 0xd1, 0x8a, 0x91, 0x72,
	0xdd, 0xec, 0x5a, 0x17, 0xe8, 0x0c, 0x82, 0x35, 0x55, 0xf3, 0x69, 0xa7, 0x7e, 0x6a, 0xaa, 0x04,
	0x7e, 0x84, 0x39, 0xbb, 0xd5, 0x7e, 0x56, 0x81, 0xfe, 0x59, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0x01, 0x4b, 0x49, 0x90, 0x04, 0x00, 0x00,
}
